# Generated by Django 5.1 on 2024-08-27 19:27

from django.db import migrations

def populate_status(apps, schemeditor):
    entries = {
        "to-do": "Issues not yet being worked on, but are on the list",
        "doing": "Issues currentlu being worked on",
        "done": "Issues completed and tested"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
