# Generated by Django 5.1 on 2024-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20240827_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='status',
            new_name='status',
        ),
    ]
