# Generated by Django 5.1 on 2024-08-27 19:50

from django.db import migrations

def populate_role(apps, schemaeditor):
    entries = {
        "scrum master": "A master of the scrum",
        "developer": "Someone who can edit others issues",
        "product owner": "owns the product"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_teams(apps, schemaeditor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_teams),
    ]
